configM:
	python3.11 -m nuitka knucleotide.python3-3.py --standalone
run:
	./knucleotide.python3-3.dist/knucleotide.python3-3.bin 0 < ../../../knucleotide-input25000000.txt

endM:
	rm -r knucleotide.python3-3.dist knucleotide.python3-3.build
