configM:
	python3.11 -m nuitka revcomp.python3-6.py --standalone
run:
	./revcomp.python3-6.dist/revcomp.python3-6.bin 0 < ../../../revcomp-input25000000.txt

endM:
	rm -r revcomp.python3-6.dist revcomp.python3-6.build