configM:
	python3.11 -m py_compile spectralnorm-d.python3-5.py
	chmod 777 __pycache__/spectralnorm-d.python3-5.cpython-311.pyc

run:
	./__pycache__/spectralnorm-d.python3-5.cpython-311.pyc 5500

endM:
	rm -r __pycache__