configM:
	python3.11 -m py_compile mandelbrot.python3-7.py
	chmod 777 __pycache__/mandelbrot.python3-7.cpython-311.pyc

run:
	./__pycache__/mandelbrot.python3-7.cpython-311.pyc 16000


endM:
	rm -r __pycache__

