configM:
	python3.11 -m py_compile revcomp.python3-6.py
	chmod 777 __pycache__/revcomp.python3-6.cpython-311.pyc

run:
	./__pycache__/revcomp.python3-6.cpython-311.pyc 0 < ../../../revcomp-input25000000.txt


endM:
	rm -r __pycache__