configM:
	python3.11 -m nuitka spectralnorm.python3-5.py --standalone
run:
	./spectralnorm.python3-5.dist/spectralnorm.python3-5.bin 5500

endM:
	rm -r spectralnorm.python3-5.dist spectralnorm.python3-5.build