configM:
	python3.11 -m py_compile knucleotide.python3-3.py
	chmod 777 __pycache__/knucleotide.python3-3.cpython-311.pyc

run:
	./__pycache__/knucleotide.python3-3.cpython-311.pyc 0 < ../../../knucleotide-input25000000.txt
endM:
	rm -r __pycache__


