configM:
	python3.11 -m py_compile regexredux.py
	chmod 777 __pycache__/regexredux.cpython-311.pyc

run:
	./__pycache__/regexredux.cpython-311.pyc 0 < ../../../regexredux-input5000000.txt


endM:
	rm -r __pycache__