configM:
	python3.11 -m nuitka fannkuchredux.python3-4.py --standalone
run:
	./fannkuchredux.python3-4.dist/fannkuchredux.python3-4.bin 12
	
endM:
	rm -r fannkuchredux.python3-4.dist fannkuchredux.python3-4.build
