configM:
	python3.11 -m py_compile fannkuchredux.python3-4.py
	chmod 777 __pycache__/fannkuchredux.python3-4.cpython-311.pyc
	
run:
	./__pycache__/fannkuchredux.python3-4.cpython-311.pyc 12
	

endM:
	rm -r __pycache__
