configM:
	python3.11 -m py_compile pidigits.python3-2.py
	chmod 777 __pycache__/pidigits.python3-2.cpython-311.pyc
run:
	./__pycache__/pidigits.python3-2.cpython-311.pyc 10000
endM:
	rm -r __pycache__