configM:
	python3.11 -m nuitka spectralnorm-d.python3-5.py --standalone
run:
	./spectralnorm-d.python3-5.dist/spectralnorm-d.python3-5.bin 5500

endM:
	rm -r spectralnorm-d.python3-5.dist spectralnorm-d.python3-5.build